import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase-server'
import Link from 'next/link'

const EU_DATABASE_STEPS = [
  {
    number: 1,
    title: 'Confirm your system is in-scope',
    detail: 'Only high-risk AI systems listed in Annex III, and GPAI models with systemic risk, must be registered. Run an assessment on each system to confirm its risk classification before registering.',
    article: 'Article 51, Annex III',
  },
  {
    number: 2,
    title: 'Create an account on the EU AI database',
    detail: 'The EU AI database is operated by the European AI Office. Access it at ec.europa.eu/transparency/ai-act. You\'ll need an EU Login account (same as other EU Commission services).',
    article: 'Article 71',
  },
  {
    number: 3,
    title: 'Prepare your registration information',
    detail: 'You\'ll need: company name and contact details, system name and version, intended purpose and deployment context, risk classification with rationale, description of training data sources, and your contact person for regulatory queries.',
    article: 'Annex VIII',
  },
  {
    number: 4,
    title: 'Submit the registration',
    detail: 'Complete the online form in the EU AI database. For high-risk systems in Annex III, registration must be completed before placing the system on the EU market or putting it into service. Keep your EU ID number — regulators will reference it.',
    article: 'Article 49',
  },
  {
    number: 5,
    title: 'Maintain and update the registration',
    detail: 'You must update the registration when there are significant changes to the system — including new versions, changes to intended purpose, or changes to your conformity assessment status. Outdated registrations can attract regulatory attention.',
    article: 'Article 51(3)',
  },
]

const TEMPLATES = [
  {
    id: 'risk-management',
    title: 'Risk Management System (Article 9)',
    description: 'Documents your ongoing process for identifying, analysing, and mitigating risks throughout the AI system lifecycle.',
    sections: ['Risk identification methodology', 'Risk analysis and evaluation criteria', 'Risk mitigation measures', 'Residual risk assessment', 'Post-market monitoring plan'],
  },
  {
    id: 'technical-doc',
    title: 'Technical Documentation (Article 11, Annex IV)',
    description: 'The full 10-section document required for high-risk AI systems. Auto-generated from your assessment via the Technical Documentation feature.',
    sections: ['General system description', 'Intended purpose', 'Development methodology', 'Training data', 'Performance metrics', 'Risk management', 'Human oversight', 'Transparency', 'Cybersecurity', 'Post-market monitoring'],
    autoGenerated: true,
  },
  {
    id: 'conformity-declaration',
    title: 'EU Declaration of Conformity (Article 47)',
    description: 'Formal declaration that your AI system meets all applicable EU AI Act requirements. Must be signed by an authorised representative.',
    sections: ['Provider identification', 'System identification and version', 'Applicable regulations and standards', 'Notified body details (if applicable)', 'Authorised signatory'],
  },
  {
    id: 'data-governance',
    title: 'Data Governance Policy (Article 10)',
    description: 'Documents your practices for training, validation, and testing data — including bias examination and data quality measures.',
    sections: ['Data collection and sourcing', 'Data quality criteria', 'Bias examination procedures', 'Data governance processes', 'Personal data handling'],
  },
  {
    id: 'human-oversight',
    title: 'Human Oversight Protocol (Article 14)',
    description: 'Defines how humans monitor and intervene in AI system operation, including override procedures and responsibility assignments.',
    sections: ['Oversight roles and responsibilities', 'Monitoring procedures', 'Intervention triggers', 'Override and stop procedures', 'Training requirements for operators'],
  },
]

export default async function GuidancePage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase.from('profiles').select('plan').eq('id', user.id).single()
  const isPaid = profile?.plan && profile.plan !== 'free'

  return (
    <div className="p-8 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-2xl font-bold">Compliance Guidance</h1>
        <p className="text-gray-400 text-sm mt-1">EU database registration and conformity assessment templates.</p>
      </div>

      {/* EU AI Database Registration */}
      <div className="mb-10">
        <div className="flex items-center gap-3 mb-5">
          <div className="w-8 h-8 bg-blue-500/20 border border-blue-500/30 rounded-lg flex items-center justify-center shrink-0">
            <svg className="w-4 h-4 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
          </div>
          <div>
            <h2 className="font-semibold">EU AI Database Registration</h2>
            <p className="text-xs text-gray-500">Required for high-risk systems before market placement · Article 49</p>
          </div>
        </div>

        <div className="space-y-3">
          {EU_DATABASE_STEPS.map(step => (
            <div key={step.number} className="flex gap-4 bg-white/5 border border-white/10 rounded-xl p-5">
              <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-sm font-bold shrink-0">
                {step.number}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-2 mb-1">
                  <h3 className="font-semibold text-sm">{step.title}</h3>
                  <span className="text-xs font-mono text-blue-400 shrink-0">{step.article}</span>
                </div>
                <p className="text-sm text-gray-400 leading-relaxed">{step.detail}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Conformity Assessment Templates */}
      <div>
        <div className="flex items-center gap-3 mb-5">
          <div className="w-8 h-8 bg-green-500/20 border border-green-500/30 rounded-lg flex items-center justify-center shrink-0">
            <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <div>
            <h2 className="font-semibold">Conformity Assessment Templates</h2>
            <p className="text-xs text-gray-500">Document templates required for high-risk AI system compliance</p>
          </div>
        </div>

        {!isPaid && (
          <div className="bg-blue-600/10 border border-blue-500/20 rounded-xl p-5 mb-5 flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold mb-0.5">Templates available on paid plans</p>
              <p className="text-xs text-gray-400">Upgrade to access all conformity assessment templates with guidance notes.</p>
            </div>
            <Link href="/dashboard/billing" className="text-sm bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg transition shrink-0">
              Upgrade →
            </Link>
          </div>
        )}

        <div className="space-y-3">
          {TEMPLATES.map(template => (
            <div key={template.id} className={`bg-white/5 border border-white/10 rounded-xl p-5 ${!isPaid ? 'opacity-50 pointer-events-none' : ''}`}>
              <div className="flex items-start justify-between gap-4 mb-3">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-semibold text-sm">{template.title}</h3>
                    {template.autoGenerated && (
                      <span className="text-xs bg-blue-500/20 text-blue-400 px-2 py-0.5 rounded-full">Auto-generated</span>
                    )}
                  </div>
                  <p className="text-xs text-gray-400">{template.description}</p>
                </div>
                {isPaid && (
                  template.autoGenerated ? (
                    <Link href="/dashboard/systems" className="text-xs text-blue-400 border border-blue-500/30 hover:bg-blue-500/10 px-3 py-1.5 rounded-lg transition shrink-0">
                      Generate →
                    </Link>
                  ) : (
                    <Link href={`/dashboard/guidance/template/${template.id}`} className="text-xs text-gray-300 border border-white/10 hover:bg-white/5 px-3 py-1.5 rounded-lg transition shrink-0">
                      View template →
                    </Link>
                  )
                )}
              </div>
              <div className="flex flex-wrap gap-2">
                {template.sections.map(s => (
                  <span key={s} className="text-xs bg-white/5 text-gray-500 px-2 py-0.5 rounded">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
