import Link from 'next/link'
import type { Metadata } from 'next'
import { ThemeToggle } from '@/components/ThemeToggle'
import { NewsletterSignup } from '@/components/NewsletterSignup'
import { RelatedGuides } from '@/components/RelatedGuides'
import { SiteNav } from '@/components/SiteNav'
import { SiteFooter } from '@/components/SiteFooter'

export const metadata: Metadata = {
  title: 'EU AI Act Article 26 Deployer Obligations, What Attaches August 2 2026',
  description: 'Article 26 of the EU AI Act applies to every deployer of a high-risk AI system from 2 August 2026. Practical breakdown of all 12 deployer obligations, what each requires, and how national workforce rules layer on top.',
  alternates: { canonical: 'https://www.getactcomply.com/eu-ai-act-deployer-obligations' },
  openGraph: {
    title: 'EU AI Act Article 26: What Attaches for Deployers on August 2',
    description: 'Article 26 is the universal trigger. All 12 deployer obligations explained, plus the practical implementation checklist for August 2 2026.',
    url: 'https://www.getactcomply.com/eu-ai-act-deployer-obligations',
  },
}

const operationalFive = [
  {
    para: 'Paragraph 1',
    title: 'Use per instructions for use',
    body: 'Deployers shall take appropriate technical and organisational measures to ensure they use the high risk AI system in accordance with the instructions for use accompanying the system. In practical terms, the provider’s instructions for use bind your operational practice. If the instructions say the system is validated only for adult subjects, you cannot deploy on minors. If they specify input data ranges, your pipeline must respect them. The instructions become enforceable as a matter of compliance, not just provider liability.',
  },
  {
    para: 'Paragraph 2',
    title: 'Human oversight by competent persons',
    body: 'Deployers shall assign human oversight to natural persons who have the necessary competence, training and authority, as well as the necessary support. Three concrete elements: competence (do they understand the system’s outputs and limitations), training (have they been trained on the specific high risk system), and authority (can they actually override the system or escalate). Oversight by a person who lacks any of these three is not Article 26 compliant.',
  },
  {
    para: 'Paragraph 4',
    title: 'Input data relevance',
    body: 'To the extent the deployer controls the input data, the deployer must ensure that input data is relevant and sufficiently representative in view of the intended purpose. This is conditional: in many SaaS deployments the input pipeline is provider-controlled. Where you do control inputs (e.g., uploading your customer dataset to a credit scoring AI), the obligation lands on you.',
  },
  {
    para: 'Paragraph 5',
    title: 'Monitor and notify',
    body: 'Deployers must monitor operation of the high risk AI system based on the instructions for use and, where relevant, inform providers of risks observed in operation. Where a deployer identifies a risk to health, safety, or fundamental rights, the deployer must notify the provider or distributor and the relevant market surveillance authority without delay and suspend use. Serious incidents trigger an immediate provider notification, followed by distributor and authority notification.',
  },
  {
    para: 'Paragraph 6',
    title: 'Log retention for at least six months',
    body: 'Deployers must keep the logs automatically generated by the high risk AI system, to the extent the logs are under the deployer’s control, for a period appropriate to the intended purpose, of at least six months, unless provided otherwise in applicable Union or national law. The "at least" floor is important: longer retention may be required under sector rules or by the provider’s instructions.',
  },
]

const transparencyTwo = [
  {
    para: 'Paragraph 7',
    title: 'Worker notification before workplace deployment',
    body: 'Before putting into service or using a high risk AI system at the workplace, employer-deployers must inform workers’ representatives and the affected workers that they will be subject to the use of the system. This obligation is independent of the consultation rights that flow through national workforce law (e.g., Germany’s BetrVG, Spain’s Ley Rider). Even where no national workforce regime applies, Article 26(7) requires the notification.',
  },
  {
    para: 'Paragraph 11',
    title: 'Individual notification before AI decisions',
    body: 'Deployers of high risk AI systems referred to in Annex III that make decisions or assist in making decisions related to natural persons must inform those persons that they are subject to the use of the high risk AI system. This is broader than Paragraph 7 because it covers any individual affected by an AI-supported decision, not only workers.',
  },
]

const complianceInterfaces = [
  {
    para: 'Paragraph 9',
    title: 'DPIA coordination',
    body: 'Deployers shall use the information provided under Article 13 of the AI Act (provider transparency obligation) to comply with their obligation to carry out a data protection impact assessment under Article 35 of the GDPR or Article 27 of the Law Enforcement Directive (Directive 2016/680), where applicable. Practical translation: when you do your GDPR DPIA for a high risk AI system, the provider’s Article 13 instructions for use document is a required input.',
  },
  {
    para: 'Paragraph 12',
    title: 'Cooperation with competent authorities',
    body: 'Deployers shall cooperate with competent authorities in any action those authorities take in relation to the high risk AI system to implement the AI Act. In practice, this means responding to information requests, providing logs and instructions for use, and supporting inspections.',
  },
]

const narrowerObligations = [
  {
    para: 'Paragraph 8',
    title: 'Public authority registration',
    body: 'Public authorities (and Union institutions, bodies, offices, and agencies) using a high risk AI system must register that use in the EU database referred to in Article 71, and must not use a system that is not registered in that database. Private commercial deployers are not subject to the registration obligation under paragraph 8.',
  },
  {
    para: 'Paragraph 10',
    title: 'Biometric identification in criminal investigations',
    body: 'Deployers using a high risk AI system for post-remote biometric identification in the context of investigating targeted searches must request authorisation by a judicial or administrative authority prior to use (or within 48 hours after the start of use, in limited circumstances). Usage must be limited to specific listed offences, documented, and reported annually. Highly relevant to law enforcement deployers, less relevant to most commercial AI use.',
  },
]

const implementationChecklist = [
  {
    title: 'Inventory',
    body: 'Identify every Annex III high risk AI system your organisation deploys. Without an inventory, the rest of the work is undefined.',
  },
  {
    title: 'Instructions for use binder',
    body: 'Collect the provider’s Article 13 instructions for use document for each high risk system. Confirm it is current. Map operational constraints (validated input ranges, intended purpose, monitoring directions) into your operational procedures.',
  },
  {
    title: 'Human oversight assignment',
    body: 'Assign a named natural person to each high risk system as the Article 26(2) oversight contact. Document their competence, training, and authority. Authority specifically means they can override or suspend system use, not just receive escalations.',
  },
  {
    title: 'Input data pipeline review',
    body: 'Where you control the input data, document how relevance and representativeness are maintained. This may involve sampling, data validation, or dataset documentation depending on the system.',
  },
  {
    title: 'Monitoring and notification process',
    body: 'Stand up a process for monitoring system operation, identifying risks, and notifying providers and market surveillance authorities. This is operational, not just policy. The notification path needs to actually work in practice.',
  },
  {
    title: 'Log retention configuration',
    body: 'Confirm automatic log generation is enabled and that retention is set to at least six months. Check sector rules for longer floors where applicable.',
  },
  {
    title: 'Worker and individual notification stack',
    body: 'Draft and deploy the Article 26(7) worker notification and the Article 26(11) individual notification. These can often be combined with existing GDPR Article 13/14 transparency notices.',
  },
  {
    title: 'DPIA refresh',
    body: 'Update existing GDPR DPIAs for high risk AI systems to incorporate provider Article 13 information. Where Article 27 FRIA also applies, document how the FRIA complements the DPIA under Article 27(3).',
  },
]

export default function DeployerObligationsPage() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 dark:bg-gray-950 dark:text-white">
      <SiteNav width="4xl">
        <Link href="/assess" className="bg-blue-600 hover:bg-blue-500 text-white text-sm px-4 py-2 rounded-lg transition font-medium">
          Assess your AI systems &rarr;
        </Link>
        <ThemeToggle />
      </SiteNav>

      <main className="max-w-4xl mx-auto px-6 py-16">

        {/* Header */}
        <div className="mb-12">
          <div className="flex flex-wrap gap-2 mb-6">
            <span className="inline-flex items-center gap-1.5 bg-blue-500/10 border border-blue-500/20 text-blue-600 dark:text-blue-400 text-xs px-3 py-1.5 rounded-full font-medium">
              Practical guide
            </span>
            <span className="inline-flex items-center gap-1.5 bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 text-gray-500 text-xs px-3 py-1.5 rounded-full">
              Updated May 18, 2026
            </span>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
            August 2:<br />
            <span className="text-blue-500 dark:text-blue-400">what attaches for deployers</span>
          </h1>

          <p className="text-xl text-gray-600 dark:text-gray-400 leading-relaxed">
            On 2 August 2026, EU AI Act Article 26 deployer obligations come into force for every high risk AI system.
            Article 27 FRIA gets the headlines, but <strong className="text-gray-900 dark:text-white">Article 26 is the universal trigger.</strong>{' '}
            Here&rsquo;s the practical breakdown of all twelve deployer obligations, what each requires in operational terms,
            and how national workforce rules layer on top.
          </p>
        </div>

        {/* Key callout */}
        <div className="bg-blue-500/10 border border-blue-500/20 rounded-2xl p-6 mb-12">
          <p className="text-sm font-semibold text-blue-600 dark:text-blue-400 mb-2">The one thing to understand</p>
          <p className="text-gray-900 dark:text-white font-medium text-lg leading-relaxed">
            Article 27 FRIA scope is narrow (public bodies, public service providers, credit/insurance deployers).
            Article 26 is universal: every Annex III high risk AI system deployer is subject to it from 2 August 2026,
            regardless of public/private status or sector. If you only read one part of the EU AI Act before August 2, read Article 26.
          </p>
        </div>

        {/* What Article 26 is */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-4">What Article 26 actually is</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            Article 27 Fundamental Rights Impact Assessment scope is narrow. It attaches to public bodies, private entities providing
            public services, and deployers of creditworthiness or insurance pricing AI. (We covered the precise scope and what fills
            the gap in <Link href="/eu-ai-act-fria-scope" className="text-blue-600 dark:text-blue-400 hover:underline">Article 27 FRIA: who it actually applies to</Link>.)
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            Article 26 is different. It applies to every deployer of a high risk AI system. Every deployer means every natural or legal
            person using a high risk system under their authority in the course of professional activity. Public body or private company,
            in-house or via SaaS, transport or e-commerce, the obligations apply.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            Article 26 is twelve paragraphs of obligations. Some operational. Some procedural. Some narrow. This article unpacks all twelve,
            grouped by what they actually require you to do.
          </p>
        </section>

        {/* Who is a deployer */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-4">Who is a deployer</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            The Regulation distinguishes two main roles along the AI value chain: provider and deployer.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            A <strong>provider</strong> places an AI system on the market or puts it into service under its own name or trademark,
            whether free of charge or for payment. OpenAI is a provider of GPT-4. Microsoft is a provider of Copilot.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            A <strong>deployer</strong> is &ldquo;a natural or legal person, public authority, agency or other body using an AI system under
            its authority except where the AI system is used in the course of a personal non-professional activity&rdquo; (Article 3(4) definition).
            A law firm using Copilot to draft contract first drafts is a deployer. A hospital using a radiology classifier is a deployer.
            A ride hailing platform using driver allocation AI is a deployer.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            One organisation can be both. If you take a provider&rsquo;s high risk system and substantially modify it
            (within the meaning of Article 25(1)(b)), you become a provider of the modified system and inherit provider obligations
            on top of deployer ones.
          </p>
        </section>

        {/* The operational five */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-2">The operational five</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Paragraphs 1, 2, 4, 5, and 6 are the operational core: how you actually use the system day to day.</p>
          <div className="space-y-4">
            {operationalFive.map((item) => (
              <div key={item.para} className="bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl p-6">
                <div className="mb-2 flex items-center gap-2">
                  <span className="text-xs font-mono text-blue-600 dark:text-blue-400">{item.para}</span>
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">{item.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{item.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* The transparency two */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-2">The transparency two</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Paragraphs 7 and 11 are the human-facing transparency obligations.</p>
          <div className="space-y-4">
            {transparencyTwo.map((item) => (
              <div key={item.para} className="bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl p-6">
                <div className="mb-2 flex items-center gap-2">
                  <span className="text-xs font-mono text-blue-600 dark:text-blue-400">{item.para}</span>
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">{item.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{item.body}</p>
              </div>
            ))}
          </div>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-6">
            Together, paragraphs 7 and 11 create a two-layer transparency stack: workers when AI is used in the workplace, and any
            affected individual when AI is used to make decisions about them. Both layers run independently of any GDPR transparency
            obligations (Articles 13, 14 GDPR), although the documentation can often be combined.
          </p>
        </section>

        {/* The compliance interfaces */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-2">The compliance interfaces</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Paragraphs 9 and 12 govern how Article 26 interacts with other rules.</p>
          <div className="space-y-4">
            {complianceInterfaces.map((item) => (
              <div key={item.para} className="bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl p-6">
                <div className="mb-2 flex items-center gap-2">
                  <span className="text-xs font-mono text-blue-600 dark:text-blue-400">{item.para}</span>
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">{item.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{item.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* The narrower obligations */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-2">The narrower obligations</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Paragraphs 8 and 10 are scope-specific.</p>
          <div className="space-y-4">
            {narrowerObligations.map((item) => (
              <div key={item.para} className="bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl p-6">
                <div className="mb-2 flex items-center gap-2">
                  <span className="text-xs font-mono text-blue-600 dark:text-blue-400">{item.para}</span>
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">{item.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{item.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* The savings clause */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-4">The savings clause</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            <span className="text-xs font-mono text-blue-600 dark:text-blue-400 mr-2">Paragraph 3</span>
            is a procedural clarifier rather than a substantive obligation. The obligations in paragraphs 1 (instructions for use compliance)
            and 2 (human oversight) do not exclude other obligations under Union or Member State law and shall not affect the deployer&rsquo;s
            freedom to organise its own resources and activities for the purpose of implementing the human oversight measures indicated by the provider.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            In practical terms: Article 26 is a floor, not a ceiling. Other rules can layer on top.
            And the way you implement human oversight in particular is for you to organise, provided the substance meets the Article 26(2)
            competence/training/authority requirements.
          </p>
        </section>

        {/* How national rules layer */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-4">How national rules layer</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            Article 26 sets the floor. Member State workforce law, sector regulation, and other Union instruments can impose additional
            obligations that operate alongside it.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            <strong>Spain&rsquo;s Ley Rider</strong> (Royal Decree-Law 9/2021, amending Article 64.4(d) of the Workers&rsquo; Statute) requires platforms
            to inform worker representatives of the parameters, rules, and instructions on which algorithms or AI systems are based when they influence
            working conditions, access to or maintenance of employment, and profiling. The Ley Rider obligation overlaps with Article 26(7) on worker
            notification but goes further on substantive content (parameters and rules, not just notification of use).
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            <strong>Germany&rsquo;s Works Constitution Act (BetrVG)</strong> gives works councils co-determination rights over technical equipment intended
            to monitor employee behaviour or performance under &sect; 87(1)(6). The Federal Labour Court has interpreted this broadly enough to cover AI based monitoring.
            The 2021 Works Council Modernization Act (Betriebsr&auml;temodernisierungsgesetz) added explicit AI provisions at &sect; 80(3) (expert consultation),
            &sect; 90(1) (planning information), and &sect; 95(2a) (AI in personnel selection guidelines). Co-determination obligations under BetrVG
            go further than Article 26(7) on procedural rights.
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
            <strong>The Platform Work Directive</strong> (Directive (EU) 2024/2831, transposition deadline 2 December 2026) will harmonise much of the
            platform-specific workforce regime across the EU. It introduces a presumption of employment for platform workers and mandatory transparency
            obligations for algorithmic management. Once transposed, the Directive will overlap substantially with both Article 26 deployer obligations
            and Article 27 FRIA (for those it applies to).
          </p>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            The implication for a deployer running workforce AI in multiple Member States: Article 26 is the universal baseline, but national workforce
            rules and the Platform Work Directive transposition add layers that vary by jurisdiction. The compliance work is to identify the union of
            obligations across your operating footprint, not just the Article 26 baseline.
          </p>
        </section>

        {/* Practical implementation */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-2">Practical implementation before August 2</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">The deliverable structure for an Article 26 readiness programme.</p>
          <div className="space-y-4">
            {implementationChecklist.map((item, i) => (
              <div key={item.title} className="bg-white dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl p-5">
                <div className="flex items-start gap-4">
                  <div className="w-7 h-7 bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-lg flex items-center justify-center text-sm font-bold shrink-0 mt-0.5">
                    {i + 1}
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 dark:text-white mb-1">{item.title}</h3>
                    <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{item.body}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-6">
            Each item is a discrete artefact your supervisory authority can ask you to produce after 2 August.
          </p>
        </section>

        {/* What FRIA adds */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold mb-4">What FRIA adds for those it applies to</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            For the subset of deployers in scope of Article 27 FRIA (public bodies, private entities providing public services,
            deployers of creditworthiness or insurance pricing AI), the FRIA layers on top of Article 26 with six structured inputs
            and a notification to the market surveillance authority. The{' '}
            <Link href="/eu-ai-act-fria-scope" className="text-blue-600 dark:text-blue-400 hover:underline">Article 27 FRIA scope guide</Link>{' '}
            covers who&rsquo;s in, who&rsquo;s out, and the working template. For everyone else, Article 26 alone is the operational target for 2 August.
          </p>
        </section>

        {/* CTA */}
        <section className="bg-blue-600 rounded-2xl p-8 text-white text-center mb-12">
          <h2 className="text-2xl font-bold mb-3">Get the Article 26 readiness analysis for your AI systems</h2>
          <p className="text-blue-100 mb-6 max-w-xl mx-auto">
            ActComply runs the Article 26 deployer classification analysis end to end. Send us one AI surface and we return
            Annex III categorisation, the specific paragraphs that attach, mapping to your existing DPIA and oversight documentation,
            and a practical implementation checklist tailored to your operating jurisdictions.
          </p>
          <Link
            href="/assess"
            className="inline-block bg-white text-blue-600 hover:bg-blue-50 font-semibold px-8 py-3 rounded-xl transition"
          >
            Assess your AI systems free &rarr;
          </Link>
          <p className="text-blue-200 text-xs mt-3">No credit card required</p>
        </section>

        {/* Related guides */}
        <RelatedGuides currentSlug="eu-ai-act-deployer-obligations" />

        {/* Newsletter signup */}
        <NewsletterSignup
          source="article-26-deployer-obligations"
          variant="card"
          heading="More August 2 readiness pieces"
          subheading="Subscribe to Builder&rsquo;s Notes for the next deep dive on EU AI Act compliance. Specific Articles, in plain English. One email when there&rsquo;s something worth saying."
        />

      </main>

      <SiteFooter
        width="4xl"
        tagline="© 2026 ActComply. Not legal advice."
        links={[
          { href: "/privacy", label: "Privacy" },
          { href: "/terms", label: "Terms" },
          { href: "/eu-ai-act-fria-scope", label: "FRIA scope guide" },
        ]}
      />
    </div>
  )
}
